import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from "@/src/components/analytics";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics/>
      <body>
        {children}
      </body>
    </html>
  );
}
